baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ortonville Farmers Market"
theme = ['alpha-church']
themesDir = "themes"

rssLimit = 5

enableEmoji = true

# Enter your tracking code to enable Google Analytics !!!
googleAnalytics = ""

[taxonomies]
  tag = "farmers"
  preacher = "market"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "About The Market"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Resources"
    url = "#"
    weight = 3

  [[menu.main]]
    name = "Become A Vendor"
    url = "/vendorinformation"
    parent = "Resources"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    parent = "Resources"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Ortonville Farmers Market"
#Update with exact dates !!!
  subtitle = "Every Saturday at 9 a.m. May-October in Downtown Ortonville" 
  author = "Aaron Martz"

  customCSS = ["example.css"]

  bible_popups = false
  instant_page = true

  [params.podcast]
# Not Using This At This Time, Leave Untouched
    title = "Listen to Alpha Church"
    subtitle = ""
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
    feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"

  [params.map]
    # For Open Street Map widgets
    latitude = "42.8522"
    longitude = "-83.4440"
    zoom = "18"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "img/oldMill.jpg"

      [[params.landing.banner.button]]
        url = "/contact"
        text = "Visit the Market"
        type = "special"

        [[params.landing.banner.button]]
        url = "#feature-icons"
        text = "Find out more"

    #Details for the box below the banner
    [params.landing.services]
      title = "Market on Saturday"
#!!!! Fix what dates it runs from
      text = "The market opens at 9 am every Saturday from May to October, rain or shine."
      map_location = "Downtown Ortonville, MI"

    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = true

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-carrot"
        icon_pack = "fas"
        accent = "1"
        title = "Shop"
        text = "Buy directly from our local community."

      [[params.landing.feature_icons.tile]]
        icon = "fa-hands-helping"
        icon_pack = "fas"
        accent = "2"
        title = "Meet"
        text = "Building community at the local level."

      [[params.landing.feature_icons.tile]]
        icon = "fa-guitar"
        icon_pack = "fas"
        accent = "5"
        title = "Play"
        text = "Crafts, music and other entertainment every Saturday."

      [[params.landing.feature_icons.tile]]
        icon = "fa-heartbeat"
        icon_pack = "fas"
        accent = "3"
        title = "Support"
        text = "Your family, local farmers, producers and our downtown."

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = true

      [[params.landing.feature_images.tile]]
        image = "img/market.jpeg"
        title = "Benefits of a Farmers Market"
        text = "Why spend your Saturday at the market?"
        url = "/benefits"
        button_text = "Learn More"

      [[params.landing.feature_images.tile]]
        image = "img/marketTruck.jpg"
        title = "Vendor Information"
        text = "Find out who is at the market!"
        url = "/vendorlist"
        button_text="Learn More"

    [params.landing.CTA]
      heading = "Get in touch!"
      message = "We'd love to hear from you."

    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "/sermons/index.xml"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
